services:
  authdb:
    image: mysql
    container_name: authdb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./src/auth-service/init.sql:/docker-entrypoint-initdb.d/init.sql
      - authdb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - auth-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: authdb
      PMA_PORT: 3306
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - auth-network

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./src/gateway/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

networks:
  auth-network:

volumes:
  authdb-data:
  mongodb-data: