services:
  authdb:
    image: mysql
    container_name: authdb
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
    volumes:
      - ./src/auth-service/init.sql:/docker-entrypoint-initdb.d/init.sql
      - authdb-data:/var/lib/mysql
    networks:
      - auth-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: authdb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpass123
    ports:
      - "8080:80"
    networks:
      - auth-network

  auth-service: 
    build: ./src/auth-service
    container_name: auth-service
    ports:
      - "3001:5000"
    depends_on:
      - authdb
    volumes:
      - ./src/auth-service:/app
    networks:
      - auth-network

  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      environment:
      - RABBITMQ_DEFAULT_USER=rabbituser
      - RABBITMQ_DEFAULT_PASS=rabbitpass
      ports:
        - 5672:5672
        - 15672:15672
      volumes:
        - rabbitmq-data:/var/lib/rabbitmq
      networks:
        - queue-network

networks:
  auth-network:
  queue-network:

volumes:
  authdb-data:
  rabbitmq-data: